install.packages('cvTools')
library(cvTools)
library(robustbase)
data(coleman)
head(coleman)
c<-call('lmrob',formula=Y~.)
folds<-cvFolds(nrow(coleman),K=5,R=10)
cvTool(c,data=coleman,y-coleman$Y,cost=rtmspe,folds=folds,costArgs = list(trim=0.1))
tuning<-list(tuning.psi=seq(2.,6.,20))
